#!/usr/bin/env bash

# Name of the private key
private_key_name="school"

# Number of bits in the key
key_bits=4096

# Passphrase for the key
passphrase="betty"

# Output file names
private_key_file=$private_key_name_private.pem
public_key_file=$private_key_name_public.pem

# Generate RSA key pair with passphrase
ssh-keygen -t rsa -b $key_bits -f $private_key_file -N $passphrase

# Display success message
echo "RSA key pair created successfully:"
echo "Private key:" $private_key_file
echo "Public key:" $public_key_file
