#! /usr/bin/env bash
# Configure an Nginx server to listen on port 80.

# remove the default Nginx configuration file
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# restart nginx
service nginx restart
