#!/usr/bin/env bash
#This Bash script is designed to transfer a file to a remote server using the scp (secure copy) command 
if [ "$#" -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -i "$4" "$1" "$3@$2" :~/
fi
