#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine nginx

apt-get -y update
apt-get -y install nginx
ufw allow  'Nginx HTTP'
sudo echo '<p>Holberton School</p>' > /var/www/html/index.nginx-debian.html
service nginx restart
