#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine nginx

apt-get -y update
apt-get -y install nginx
ufw allow  'Nginx HTTP'
sudo echo "<p>Holberton School</p>" | sudo tee /var/www/html/index.html
sudo service nginx restart
